package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.BorderFactory;

public class ConnectFourInterfaceMenu extends javax.swing.JFrame
{

    // Other classes to leverage
    private Thread animationThread;
    public static ConnectFourInterfacePanel interfacePanel;
    private static DrawingHandyman handyman;

    /**
     * Creates new form PathfinderInterface
     */
    public ConnectFourInterfaceMenu()
    {
        // Netbeans autogenerated init
        initComponents();
        // Add the JPanel class to the JFrame
        initPanel();
        // Center the window
        this.setLocationRelativeTo(null);
    }

    // Dynamically add PathfinderInterfacePanel class to the visualization panel
    private void initPanel()
    {
        int rows = 6;
        int columns = 7;
        // Create panel
        interfacePanel = new ConnectFourInterfacePanel(mainPanel.getWidth(), mainPanel.getHeight(),
                columns);
        // Clear panel
        mainPanel.removeAll();
        // Border
        mainPanel.setBorder(BorderFactory.createLineBorder(Color.black));
        // Layout
        mainPanel.setLayout(new java.awt.BorderLayout());

        // Add interfacePanel
        mainPanel.add(interfacePanel, BorderLayout.CENTER);
        mainPanel.validate();

        // Start interfacePanel thread
        animationThread = new Thread(interfacePanel);
        animationThread.start();

        this.handyman = new DrawingHandyman(rows);
    }

    // Write out the percentages for each column
    public static void updatePercentages(HashMap<Integer, Double> percentages)
    {
        column1Label.setText(percentages.get(0).toString());
        column2Label.setText(percentages.get(1).toString());
        column3Label.setText(percentages.get(2).toString());
        column4Label.setText(percentages.get(3).toString());
        column5Label.setText(percentages.get(4).toString());
        column6Label.setText(percentages.get(5).toString());
        column7Label.setText(percentages.get(6).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        column1Label = new javax.swing.JLabel();
        column2Label = new javax.swing.JLabel();
        column3Label = new javax.swing.JLabel();
        column4Label = new javax.swing.JLabel();
        column5Label = new javax.swing.JLabel();
        column6Label = new javax.swing.JLabel();
        column7Label = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pathfinding Visualizer");
        setResizable(false);

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153,
                153)));
        mainPanel.setPreferredSize(new java.awt.Dimension(701, 700));
        mainPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                mainPanelMouseMoved(evt);
            }
        });
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                mainPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(mainPanelLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 699, Short.MAX_VALUE));
        mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 698, Short.MAX_VALUE));

        column1Label.setBorder(javax.swing.BorderFactory.createEtchedBorder(
                java.awt.Color.lightGray, null));
        column1Label.setPreferredSize(new java.awt.Dimension(80, 14));

        column2Label.setBorder(javax.swing.BorderFactory.createEtchedBorder(
                java.awt.Color.lightGray, null));
        column2Label.setPreferredSize(new java.awt.Dimension(80, 14));

        column3Label.setBorder(javax.swing.BorderFactory.createEtchedBorder(
                java.awt.Color.lightGray, null));
        column3Label.setPreferredSize(new java.awt.Dimension(80, 14));

        column4Label.setBorder(javax.swing.BorderFactory.createEtchedBorder(
                java.awt.Color.lightGray, null));
        column4Label.setPreferredSize(new java.awt.Dimension(80, 14));

        column5Label.setBorder(javax.swing.BorderFactory.createEtchedBorder(
                java.awt.Color.lightGray, null));
        column5Label.setPreferredSize(new java.awt.Dimension(80, 14));

        column6Label.setBorder(javax.swing.BorderFactory.createEtchedBorder(
                java.awt.Color.lightGray, null));
        column6Label.setPreferredSize(new java.awt.Dimension(80, 14));

        column7Label.setBorder(javax.swing.BorderFactory.createEtchedBorder(
                java.awt.Color.lightGray, null));
        column7Label.setPreferredSize(new java.awt.Dimension(80, 14));

        restartButton.setText("Restart");
        restartButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                restartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(mainPanel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(
                                                                        column1Label,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)
                                                                .addComponent(
                                                                        column2Label,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)
                                                                .addComponent(
                                                                        column3Label,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)
                                                                .addComponent(
                                                                        column4Label,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)
                                                                .addComponent(
                                                                        column5Label,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)
                                                                .addComponent(
                                                                        column6Label,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(20, 20, 20)
                                                                .addComponent(
                                                                        column7Label,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(restartButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(restartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(
                                layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(column1Label,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(column2Label,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(column3Label,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(column4Label,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(column5Label,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(column6Label,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(column7Label,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPanelMouseMoved(java.awt.event.MouseEvent evt)
    {// GEN-FIRST:event_mainPanelMouseMoved
        handyman.requestColumnHighlight(evt.getX(), evt.getY());
    }// GEN-LAST:event_mainPanelMouseMoved

    private void mainPanelMouseClicked(java.awt.event.MouseEvent evt)
    {// GEN-FIRST:event_mainPanelMouseClicked
        handyman.requestMove(evt.getX(), evt.getY(), true);
    }// GEN-LAST:event_mainPanelMouseClicked

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_restartButtonActionPerformed

    }// GEN-LAST:event_restartButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel column1Label;
    private static javax.swing.JLabel column2Label;
    private static javax.swing.JLabel column3Label;
    private static javax.swing.JLabel column4Label;
    private static javax.swing.JLabel column5Label;
    private static javax.swing.JLabel column6Label;
    private static javax.swing.JLabel column7Label;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton restartButton;
    // End of variables declaration//GEN-END:variables
}
